apiVersion: apps/v1
kind: Deployment
metadata:
  name: krop-controller
spec:
  template:
    spec:
      hostAliases:
        - ip: "10.96.188.4"
          hostnames:
            - "localhost"
            - "portal.localhost"
            - "kcp.localhost"
            - "root.kcp.localhost"
            - "kcp.api.portal.localhost"
            - "nereus.kcp.localhost"
            - "triton.kcp.localhost"
